export enum Condition {
    BLINDED = "BLINDED",
    CHARMED = "CHARMED",
    DEAFENED = "DEAFENED",
    FRIGHTENED = "FRIGHTENED",
    GRAPPLED = "GRAPPLED",
    INCAPACITATED = "INCAPACITATED",
    INVISIBLE = "INVISIBLE",
    PARALYZED = "PARALYZED",
    PETRIFIED = "PETRIFIED",
    POISONED = "POISONED",
    PRONE = "PRONE",
    RESTRAINED = "RESTRAINED",
    STUNNED = "STUNNED",
    UNCONSCIOUS = "UNCONSCIOUS",
    EXHAUSTION = "EXHAUSTION"
}