export enum ModalTypeEnum {
    DND_CHARACTER = "DND_CHARACTER",
    CREATURE = "CREATURE",
    CREATURE_ON_MAP = "CREATURE_ON_MAP",
    CREATURE_ON_PLAYER_MAP = "CREATURE_ON_PLAYER_MAP",
    CREATURE_PLAYER = "CREATURE_PLAYER",
}